### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by AlexDvorak** [awtybots/FRC-2021#5]
- diagnostics
    - [x] flywheel rpm
    - [x] drive percent output left/right
    - [x] perceived limelight distance
- shooter
    - [x] turret code yesterday
    - [x] limelight tracking
    - [x] adjustable hood
    - [x] (like) limelight determine adj hood + sspeed
- [x] separate tower/spindexer subsystems
- main
    - [x] LEAVE FOR LAST alliance color LEDs
